name: Push File

on:
  push:
    branches:
      - main

jobs:
  push-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Add file
        run: echo "Hello, World!" > new_file.txt
      
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GTOKEN }}
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add new file via GitHub Action"
          git push origin main
