name: Push File

on:
  push:
    branches:
      - main

jobs:
  push-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Add file
        run: echo "Hello, World!" > new_file.txt
      
      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git remote add origin_with_token https://${{ secrets.GTOKEN }}@github.com/thanhtayt/Ninov2.git
      
      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Add new file via GitHub Action"
          git push origin_with_token main
